### ISSUE TITLE
NCAAF Current season (2019) teams.schedule.dataframe_extended is NoneType

### ISSUE THREAD

**Issue by naymikm** [roclark/sportsreference#184]
**Describe the bug**
The basic dataframe is working but the dataframe_extended is NoneType

**To Reproduce**
>>> from sportsreference.ncaaf.teams import Teams
>>> teams = Teams(year=2019)
>>> team = teams['KANSAS']
>>> team.schedule.dataframe

    boxscore_index          date            datetime  ... streak      time  wins
    2019-08-31-kansas                    2019-08-31-kansas  Aug 31, 2019 2019-08-31 12:00:00  ...    W 1  12:00 PM     1
    2019-09-07-kansas                    2019-09-07-kansas   Sep 7, 2019 2019-09-07 19:00:00  ...          7:00 PM  None
    2019-09-13-boston-college    2019-09-13-boston-college  Sep 13, 2019 2019-09-13 19:30:00  ...          7:30 PM  None
...

>>> team.schedule.dataframe_extended

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Marcus\AppData\Local\Programs\Python\Python36\lib\site-packages\sportsreference\ncaaf\schedule.py", line 482, in dataframe_extended
    df = game.dataframe_extended
  File "C:\Users\Marcus\AppData\Local\Programs\Python\Python36\lib\site-packages\sportsreference\ncaaf\schedule.py", line 161, in dataframe_extended
    return self.boxscore.dataframe
  File "C:\Users\Marcus\AppData\Local\Programs\Python\Python36\lib\site-packages\sportsreference\ncaaf\boxscore.py", line 750, in dataframe
    'losing_abbr': self.losing_abbr,
  File "C:\Users\Marcus\AppData\Local\Programs\Python\Python36\lib\site-packages\sportsreference\ncaaf\boxscore.py", line 847, in losing_abbr
    if self.winner == HOME:
  File "C:\Users\Marcus\AppData\Local\Programs\Python\Python36\lib\site-packages\sportsreference\ncaaf\boxscore.py", line 804, in winner
    if self.home_points > self.away_points:
TypeError: '>' not supported between instances of 'NoneType' and 'NoneType'

```

**Desktop (please complete the following information):**
 - OS: Windows 10
 -sportsreference==0.4.3

**Comment by roclark** [comment]
Hello again @naymikm! Thanks for informing me of this issue! Looks like the way that the team at sports-reference.com formats their boxscore pages is ever so slightly different this season, and the score now shows as an empty string instead of `None` as it previously did. I added an additional check in the `Boxscore` class to see if any of the scores are `None` or `''`, and if so, return `None` for the boxscore as it is invalid. This will only occur for games that haven't been played yet as there is no boxscore information to pull from them.

I have a fix already created and will post a PR shortly. Thanks again!

**Comment by naymikm** [comment]
Thanks! Love your work btw this package is awesome!
