### ISSUE TITLE
"lxml.etree.ParserError: Document is empty" when requesting roster of 2018 'CHO' team

### ISSUE THREAD

**Issue by cvauclair** [roclark/sportsreference#337]
When trying to get the Charlotte Hornets' roster for the 2018 season, the html parser raises a "Document is empty" exception.

Code to reproduce the error:
```python
from sportsreference.nba.teams import Teams

teams = Teams(2018)
cho = teams('CHO')
roster = cho.roster
```
Output:
```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    roster = cho.roster
  File "/home/christophe/.conda/envs/db/lib/python3.8/site-packages/sportsreference/nba/teams.py", line 209, in roster
    return Roster(self._abbreviation, self._year)
  File "/home/christophe/.conda/envs/db/lib/python3.8/site-packages/sportsreference/nba/roster.py", line 1203, in __init__
    self._find_players(year)
  File "/home/christophe/.conda/envs/db/lib/python3.8/site-packages/sportsreference/nba/roster.py", line 1329, in _find_players
    player_instance = Player(player_id)
  File "/home/christophe/.conda/envs/db/lib/python3.8/site-packages/sportsreference/nba/roster.py", line 170, in __init__
    player_data = self._pull_player_data()
  File "/home/christophe/.conda/envs/db/lib/python3.8/site-packages/sportsreference/nba/roster.py", line 488, in _pull_player_data
    player_info = self._retrieve_html_page()
  File "/home/christophe/.conda/envs/db/lib/python3.8/site-packages/sportsreference/nba/roster.py", line 208, in _retrieve_html_page
    url_data = pq(url)
  File "/home/christophe/.conda/envs/db/lib/python3.8/site-packages/pyquery/pyquery.py", line 231, in __init__
    elements = fromstring(html, self.parser)
  File "/home/christophe/.conda/envs/db/lib/python3.8/site-packages/pyquery/pyquery.py", line 120, in fromstring
    result = custom_parser(context)
  File "/home/christophe/.conda/envs/db/lib/python3.8/site-packages/lxml/html/__init__.py", line 875, in fromstring
    doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
  File "/home/christophe/.conda/envs/db/lib/python3.8/site-packages/lxml/html/__init__.py", line 763, in document_fromstring
    raise etree.ParserError(
lxml.etree.ParserError: Document is empty
```

System information
 - OS: Arch Linux
 - Python: 3.8.1
 - Sportsreference Version 0.4.7

Note:
The same code works for all other teams, season combinations that I have tried so far. The Charlotte Hornets' roster for the 2018 season seems to be the exception for some reason.

**Comment by roclark** [comment]
Hello @cvauclair, thanks for creating this issue and bringing this to my attention! I apologize for the delay here, and fortunately/unfortunately, it appears this has resolved itself as I am able to run your code and get the Hornet's 2018 roster without errors. My guess is the page on sports-reference.com was invalid for a time, causing the error here, but has since been restored by the sports-reference team.

That doesn't give me a warm and fuzzy feeling though since we are prone to future issues like this if another roster becomes invalid at some point. As such, I created a little patch that should handle this error if a similar situation comes up. THANK YOU for the detailed report as I was able to track this down and create a patch, even though it isn't reproducible anymore.

I will merge the patch shortly so we can get this resolved for the future, but please let me know if you are still running into issues and I will take a deeper look into this.

Thanks again!
